-- Execute este arquivo no Supabase Dashboard > SQL Editor
-- Corrige os textos com acentuação corrompida

UPDATE public.ameas_site_content SET value = 'Esporte adaptado. Inclusão que transforma.'                                                                                                                                          WHERE key = 'hero_title';
UPDATE public.ameas_site_content SET value = 'A AMEAS promove acolhimento, autonomia e superação por meio do esporte adaptado em São Roque e região.'                                                                               WHERE key = 'hero_subtitle';
UPDATE public.ameas_site_content SET value = 'A AMEAS é uma associação que acredita no esporte como caminho de inclusão, desenvolvimento e pertencimento para pessoas com deficiência e suas famílias.'                             WHERE key = 'about_text';
UPDATE public.ameas_site_content SET value = 'Karina Meneguini representa a liderança que aproxima pessoas, organiza esforços e transforma propósito em ação. Sua trajetória é marcada pela dedicação ao esporte adaptado, pelo cuidado com as famílias e pela construção de oportunidades reais de superação.' WHERE key = 'founder_bio1';
UPDATE public.ameas_site_content SET value = 'À frente da AMEAS, inspira atletas, voluntários e parceiros a acreditarem em um ambiente mais inclusivo, acolhedor e comprometido com o desenvolvimento de cada pessoa.'             WHERE key = 'founder_bio2';
UPDATE public.ameas_site_content SET value = 'A AMEAS mostra que o esporte também é pertencimento. Cada treino fortalece o corpo, a confiança e os vínculos.'                                                                      WHERE key = 'test1_quote';
UPDATE public.ameas_site_content SET value = 'Família atendida'                                                                                                                                                                    WHERE key = 'test1_author';
UPDATE public.ameas_site_content SET value = 'Ver a evolução dos atletas é acompanhar histórias de coragem sendo escritas com apoio, técnica e afeto.'                                                                             WHERE key = 'test2_quote';
UPDATE public.ameas_site_content SET value = 'Parceiro institucional'                                                                                                                                                              WHERE key = 'test2_author';
UPDATE public.ameas_site_content SET value = 'Aqui a superação acontece em equipe. O incentivo certo transforma limites em novas conquistas.'                                                                                      WHERE key = 'test3_quote';
UPDATE public.ameas_site_content SET value = 'Atleta AMEAS'                                                                                                                                                                        WHERE key = 'test3_author';
UPDATE public.ameas_site_content SET value = 'Seja Voluntário(a)'                                                                                                                                                                  WHERE key = 'volunteer_title';
UPDATE public.ameas_site_content SET value = 'Venha fazer parte da AMEAS! Precisamos de voluntários para apoiar treinos, eventos, atividades administrativas e muito mais. Cada hora doada transforma vidas.'                      WHERE key = 'volunteer_desc';
UPDATE public.ameas_site_content SET value = 'Secretário(a) Geral'                                                                                                                                                                WHERE key = 'org_sec1_name';
UPDATE public.ameas_site_content SET value = 'Secretário(a) Adjunto(a)'                                                                                                                                                           WHERE key = 'org_sec2_name';
UPDATE public.ameas_site_content SET value = 'Tesoureiro(a) Geral'                                                                                                                                                                WHERE key = 'org_treas1_name';
UPDATE public.ameas_site_content SET value = 'Tesoureiro(a) Adjunto(a)'                                                                                                                                                           WHERE key = 'org_treas2_name';
UPDATE public.ameas_site_content SET value = 'Fiscal Geral'                                                                                                                                                                        WHERE key = 'org_audit1_name';
UPDATE public.ameas_site_content SET value = 'Fiscal Adjunto(a)'                                                                                                                                                                  WHERE key = 'org_audit2_name';
